#BURN_ADDRESS = "gburnXXXXXXXXXXXXXXXXXXXXXXXWrcyQK"
BURN_ADDRESS = "rJVQgTnT2BmESeRnWMA5FEZVvFbfQvu2pp"
REDUCTION_HEIGHT = 1286000
# TOKEN_GENESIS = 1781860
TOKEN_GENESIS = 1
CURRENCY = "RCI"
DECIMALS = 8

# Mainnet
P2PKH_VERBYTE = bytes.fromhex("6E")
P2SH_VERBYTES = bytes.fromhex("6E")

# Regtest
# P2PKH_VERBYTE = bytes.fromhex("8B")
# P2SH_VERBYTES = bytes.fromhex("13")
